### ISSUE TITLE
Link to Community Forum broken

### ISSUE THREAD

**Issue by zonkmachine** [pioneerspacesim/pioneer-web#8]
Hi!

On the [pioneerspacesim main page](pioneerspacesim.net/) the Community forum link seem to be broken.

` <a href='http://spacesimcentral.com/ssc/forum/23-pioneer/'>Community forum</a>`

Now to be found at:
`http://spacesimcentral.com/forum/categories/pioneer`

**Comment by impaktor** [comment]
Fixed in source. Server will update soonish.

**Comment by impaktor** [comment]
@zonkmachine fixed for real now, thanks for reporting!
